@echo off
setlocal enabledelayedexpansion

echo ========================================
echo Conch Cross-Platform - VS2022 Build
echo ========================================

:: 1. Create build directory if it does not exist
if not exist "build_vs2022" (
    echo [INFO] Creating build directory 'build_vs2022'...
    mkdir build_vs2022
)
cd build_vs2022

:: 2. [CRITICAL FIX] Auto-detect system environment (OS, Compiler)
:: This generates a default Conan profile so you don't get the "profile missing" error.
echo [1/5] Detecting Conan profile...
conan profile detect --force
if %errorlevel% neq 0 (
    echo [ERROR] Failed to detect Conan profile. Please check your Conan installation.
    exit /b %errorlevel%
)

:: 3. Install Conan dependencies
:: We use the detected profile. 'tools.system.package_manager:mode=install' ensures missing tools are installed if needed.
echo [2/5] Installing Conan dependencies...
conan install .. ^
  --build=missing ^
  --settings=build_type=Release ^
  -c tools.system.package_manager:mode=install
if %errorlevel% neq 0 (
    echo [ERROR] Conan install failed. Exiting.
    exit /b %errorlevel%
)

:: 4. Generate Visual Studio 2022 Solution
:: We explicitly tell CMake to use the toolchain file generated by Conan in step 3.
echo [3/5] Generating Visual Studio 2022 solution...
cmake .. -G "Visual Studio 17 2022" -A x64 ^
  -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake ^
  -DCMAKE_POLICY_DEFAULT_CMP0091=NEW ^
  -DCMAKE_BUILD_TYPE=Release
if %errorlevel% neq 0 (
    echo [ERROR] CMake configuration failed. Exiting.
    exit /b %errorlevel%
)

:: 5. Build the project
:: Using --parallel to speed up compilation on multi-core CPUs.
echo [4/5] Building project (Release)...
cmake --build . --config Release --parallel
if %errorlevel% neq 0 (
    echo [ERROR] Build failed. Exiting.
    exit /b %errorlevel%
)

echo.
echo [5/5] Build complete!
echo.
echo Solution file: %CD%\ConchCrossPlatform.sln
echo Binaries:      %CD%\bin\Release\
echo.
echo To open in Visual Studio 2022:
echo    start build_vs2022\ConchCrossPlatform.sln
echo.

endlocal
